COMMENT =		free firmware for Atheros AR7010

# if this port is updated, sysutils/firmware/athn must be bumped
ATH9K_FIRMWARE =	magpie

CONFIGURE_ARGS +=	-DTARGET_MAGPIE=On \
			-DCMAKE_POLICY_VERSION_MINIMUM=3.5

.include <bsd.port.mk>
