COMMENT =		megaglest game data files
GH_PROJECT =		megaglest-data
REVISION =		1

RUN_DEPENDS = 		devel/desktop-file-utils
CONFIGURE_ARGS += 	-DMEGAGLEST_MENU_INSTALL_PATH="" \
			-DCMAKE_POLICY_VERSION_MINIMUM=3.5

NO_BUILD = 		Yes
PKG_ARCH = 		*

.include <bsd.port.mk>
