COMMENT =	VAAPI legacy driver for Intel GMA 4500 to UHD 630

GH_ACCOUNT =	intel
GH_PROJECT =	intel-vaapi-driver
GH_TAGNAME =	2.4.1

CATEGORIES = graphics multimedia

#Generic License inside the COPYING file.  Permits all.
PERMIT_PACKAGE=	Yes

WANTLIB += drm drm_intel m

MODULES =	devel/meson

.include <bsd.port.mk>
