COMMENT =	collection of plugins to handle mobipocket files

DISTNAME =	kdegraphics-mobipocket-${VERSION}
PKGNAME =	kdegraphics-mobipocket-kf5-${VERSION}

CATEGORIES =	devel

SHARED_LIBS +=	QMobipocket6              0.0 # 0.0

WANTLIB += ${COMPILER_LIBCXX} GL Qt6Core Qt6Gui m

NO_TEST =	Yes

.include <bsd.port.mk>
